name: Aspire-jobs CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: cd server
      run: npm install
      run: cd ..
      run: cd client
      run: npm install

    - name: Build client
      run: cd client
      run: npm start

    - name: Build server
      run: cd ..
      run: cd server
      run: node main.js

    - name: Test
      run: npm test
